kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployments 
  labels:
    app: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app 
          image: transachnhat/react-app 
          ports:
            - containerPort: 3000 

---
kind: Service
apiVersion: v1
metadata:
  name: services 
spec:
  selector:
    app: react-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000 
